"""create products table

Revision ID: 452206574d60
Revises: ffdc0a98111c
Create Date: 2022-01-09 17:47:50.965950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452206574d60'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(scale=2, precision=5, asdecimal=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('imageUrl', sa.String(length=280), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('franchise', sa.String(length=50), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
